package visao;

import javax.swing.JComboBox;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Amigo;
import modelo.Ferramenta;
import service.AmigoService;
import service.EmprestimoService;
import service.FerramentaService;

public class FrmCadastroEmprestimo extends javax.swing.JFrame {

    private transient AmigoService amigoService = new AmigoService();
    private transient FerramentaService ferramentaService= new FerramentaService();

    private String mensagem;

    public FrmCadastroEmprestimo() {
        initComponents();
        carregaCBFerramenta();
        carregaCBAmigo();
    }

    public String getMensagem() {
        return mensagem;
    }

    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCBFerramenta = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jCBAmigo = new javax.swing.JComboBox<>();
        jBCancelar = new javax.swing.JButton();
        jBCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Empréstimo");

        jLabel1.setText("Ferramenta:");

        jCBFerramenta.setToolTipText("");

        jLabel2.setText("Amigo:");

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(this::jBCancelarActionPerformed);

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(this::jBCadastrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(jBCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBCancelar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jCBFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBCadastrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        if (evt == null) return;
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        if (evt == null) return;
        try {
            int conf = 0;

            int posicaoFerramenta = jCBFerramenta.getSelectedIndex();
            int posicaoAmigo = jCBAmigo.getSelectedIndex();
            List<Ferramenta> listaFerramenta = ferramentaService.listaFerramenta();
            List<Amigo> listaAmigo = amigoService.listaAmigo();
            EmprestimoService emprestimo = new EmprestimoService();
            if ("Não".equals(ferramentaService.getDisponivel(listaFerramenta.get(posicaoFerramenta).getIdFerramenta()))) {
                mostrarMensagem("Ferramenta já emprestada.");
                throw new Erro("Ferramenta já emprestada.");
            }
            int idAmigo = listaAmigo.get(posicaoAmigo).getIdAmigo();
            if (amigoService.possuiEmprestimoAtivo(idAmigo)) {
                conf = confirmarCadastrarAmigoComEmprestimo();
            }
            int idFerramenta = listaFerramenta.get(posicaoFerramenta).getIdFerramenta();
            String dataInicio = LocalDate.now() + "";
            String[] inversaoData = dataInicio.split("-");
            dataInicio = inversaoData[2] + "-" + inversaoData[1] + "-" + inversaoData[0];
            if (conf == 0 && emprestimo.insertEmprestimoDB(idAmigo, idFerramenta, dataInicio)) {
                mostrarMensagem("Empréstimo cadastrado com sucesso.");
                ferramentaService.updateFerramentaDB(idFerramenta, listaFerramenta.get(posicaoFerramenta).getNomeFerramenta(), listaFerramenta.get(posicaoFerramenta).getMarcaFerramenta(), listaFerramenta.get(posicaoFerramenta).getCustoFerramenta());
            }
        } catch (Erro erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jBCadastrarActionPerformed
    public void carregaCBFerramenta() {
        List<Ferramenta> listaFerramenta = ferramentaService.listaFerramenta();
        for (Ferramenta objeto : listaFerramenta) {
            jCBFerramenta.addItem(objeto.getIdFerramenta() + "- " + objeto.getNomeFerramenta());
        }

    }

    public void carregaCBAmigo() {
        List<Amigo> listaAmigo = amigoService.listaAmigo();
        for (Amigo objeto : listaAmigo) {
            jCBAmigo.addItem(objeto.getIdAmigo() + "- " + objeto.getNomeAmigo());
        }

    }

    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCadastroEmprestimo().setVisible(true));

    }

    protected int confirmarCadastrarAmigoComEmprestimo() {
        return JOptionPane.showConfirmDialog(null, "Este amigo já possui um empréstimo ativo, deseja continuar?");
    }

    public void mostrarMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }

    protected javax.swing.JButton getJBCadastrar() {
        return this.jBCadastrar;
    }

    public JComboBox<String> getJCBAmigo() {
        return jCBAmigo;
    }

    public JComboBox<String> getJCBFerramenta() {
        return jCBFerramenta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JComboBox<String> jCBAmigo;
    private javax.swing.JComboBox<String> jCBFerramenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
