package visao;

import javax.swing.JOptionPane;
import modelo.Amigo;
import service.AmigoService;

public class FrmCadastroAmigo extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastroAmigo
     */
    private final transient Amigo objetoamigo;
    // cria o vínculo com Amigo.java
    private final transient AmigoService serviceAmigo;

    private String mensagem;

    public FrmCadastroAmigo() {
        initComponents();
        this.objetoamigo = new Amigo();
        // carrega o objeto vazio de amigo
        this.serviceAmigo = new AmigoService();

        cadastrarButton.addActionListener(this::cadastrarButtonActionPerformed);
        buttonLimpar.addActionListener(this::buttonLimparActionPerformed);
        cancelarButton.addActionListener(this::cancelarButtonActionPerformed);
    }

    public String getMensagem() {
        return mensagem;
    }

    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNomeAmigo = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        textNomeAmigo = new javax.swing.JTextField();
        textTelefone = new javax.swing.JTextField();
        cadastrarButton = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Amigos");

        labelNomeAmigo.setText("Nome:");

        labelTelefone.setText("Telefone:");

        cadastrarButton.setText("Cadastrar");

        buttonLimpar.setText("Limpar");

        cancelarButton.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(cadastrarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTelefone)
                            .addComponent(labelNomeAmigo)
                            .addComponent(textNomeAmigo)
                            .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelNomeAmigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNomeAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarButton)
                    .addComponent(buttonLimpar)
                    .addComponent(cancelarButton))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        //Libera todos os recurso da interface gráfica
        if (evt == null) return;
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed
 
    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        if (evt == null) return;
        textNomeAmigo.setText("");
        textTelefone.setText("");
    }//GEN-LAST:event_buttonLimparActionPerformed
    
    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        if (evt == null) return;
        try {
            String nome = "";
            String telefone = "";

            if (textNomeAmigo.getText().length() < 3) {
                mostrarMensagem("Amigo Invalido.");
                throw new Erro("Nome do amigo deve conter mais de 3 caracteres, tente novamente.");
            } else {
                nome = textNomeAmigo.getText();
            }

            if (textTelefone.getText().length() < 8) {
                mostrarMensagem("Telefone Invalido.");
                throw new Erro("Número de telefone inválido.");
            } else {
                telefone = textTelefone.getText();
            }

            // Usando o objetoamigo que já foi instanciado no construtor
            objetoamigo.setNomeAmigo(nome);
            objetoamigo.setTelefone(telefone);

            if (serviceAmigo.insertAmigoDB(nome, telefone)) {
                mostrarMensagem("Amigo cadastrado com sucesso.");
                textNomeAmigo.setText("");
                textTelefone.setText("");
            }
        } catch (Erro erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(() -> new FrmCadastroAmigo().setVisible(true));

    }

    public void mostrarMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }

    protected javax.swing.JTextField getJTFNomeAmigo() {
        return this.textNomeAmigo;  // acesso direto porque está dentro da classe
    }

    protected javax.swing.JTextField getJTFTelefone() {
        return this.textTelefone;
    }

    protected javax.swing.JButton getJBCadastrar() {
        return this.cadastrarButton;
    }

    protected javax.swing.JButton getJBLimpar() {
        return this.buttonLimpar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel labelNomeAmigo;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JTextField textNomeAmigo;
    private javax.swing.JTextField textTelefone;
    // End of variables declaration//GEN-END:variables
}
