package visao;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Emprestimo;
import service.EmprestimoService;

public class FrmGerenciarEmprestimo extends javax.swing.JFrame {

    private transient EmprestimoService emprestimoService;
    

    private String mensagem;

    public FrmGerenciarEmprestimo() {
        initComponents();
        this.emprestimoService = new EmprestimoService();
        this.CarregaListaEmprestimo();
    }

    public String getMensagem() {
        return mensagem;
    }

    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmprestimo = new javax.swing.JTable();
        labelId = new javax.swing.JLabel();
        labelIid = new javax.swing.JLabel();
        labelIdAmigo = new javax.swing.JLabel();
        labelIdFerramenta = new javax.swing.JLabel();
        labelDataInicio = new javax.swing.JLabel();
        labelDataDevolucao = new javax.swing.JLabel();
        labelAtivoConstante = new javax.swing.JLabel();
        JBCancelar = new javax.swing.JButton();
        buttonApagar = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        textIdAmigo = new javax.swing.JTextField();
        textIdFerramenta = new javax.swing.JTextField();
        textDataEmprestimo = new javax.swing.JTextField();
        textDataDevolucao = new javax.swing.JTextField();
        labelAtivo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Empréstimos");

        tableEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Empréstimo", "ID Amigo", "ID Ferramenta", "Data Início", "Data Devolução", "Empréstimo Ativo"
            }
        ));

        tableEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEmprestimoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEmprestimo);

        labelId.setText("ID Empréstimo:");

        labelIid.setText("0");

        labelIdAmigo.setText("ID Amigo:");

        labelIdFerramenta.setText("ID Ferramenta:");

        labelDataInicio.setText("Data Início:");

        labelDataDevolucao.setText("Data Devolução:");

        labelAtivoConstante.setText("Empréstimo Ativo:");

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(this::JBCancelarActionPerformed);

        buttonApagar.setText("Apagar");
        buttonApagar.addActionListener(this::buttonApagarActionPerformed);

        buttonModificar.setText("Modificar");
        buttonModificar.addActionListener(this::buttonModificarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonApagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelAtivoConstante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelIid))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelIdFerramenta)
                                    .addComponent(labelIdAmigo)
                                    .addComponent(labelDataInicio)
                                    .addComponent(labelDataDevolucao, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textDataDevolucao, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(textDataEmprestimo)
                                    .addComponent(textIdFerramenta)
                                    .addComponent(textIdAmigo))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(labelIid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIdAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIdFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdFerramenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDataInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDataDevolucao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAtivoConstante)
                    .addComponent(labelAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBCancelar)
                    .addComponent(buttonApagar)
                    .addComponent(buttonModificar))
                .addGap(15, 15, 15))
        );

        textIdAmigo.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
    //Libera todos os recurso da interface gráfica
        if (evt == null) return;

        this.dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        if (evt == null) return;

        String dataDevolucao = null;
        int id = Integer.parseInt(tableEmprestimo.getValueAt(this.tableEmprestimo.getSelectedRow(), 0).toString());
        int idAmigo = Integer.parseInt(textIdAmigo.getText());
        int idFerramenta = Integer.parseInt(textIdFerramenta.getText());
        String dataEmprestimo = textDataEmprestimo.getText();
        dataDevolucao = textDataDevolucao.getText();
        if (emprestimoService.updateEmprestimoDB(id, idAmigo, idFerramenta, dataEmprestimo, dataDevolucao)) {
            mostrarMensagem("Empréstimo atualizado com sucesso.");
            labelIid.setVisible(false);
            textIdAmigo.setText("");
            textIdFerramenta.setText("");
            textDataEmprestimo.setText("");
            textDataDevolucao.setText("");
            this.CarregaListaEmprestimo();
        }
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void tableEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEmprestimoMouseClicked
        if (evt == null) return;

        if (this.tableEmprestimo.getSelectedRow() != -1) {
            labelIid.setText(tableEmprestimo.getValueAt(this.tableEmprestimo.getSelectedRow(), 0).toString());
            labelIid.setVisible(true);
            textIdAmigo.setText(tableEmprestimo.getValueAt(this.tableEmprestimo.getSelectedRow(), 1).toString());
            textIdFerramenta.setText(tableEmprestimo.getValueAt(this.tableEmprestimo.getSelectedRow(), 2).toString());
            textDataEmprestimo.setText(tableEmprestimo.getValueAt(this.tableEmprestimo.getSelectedRow(), 3).toString());
            labelAtivoConstante.setText("Empréstimo Ativo: " + tableEmprestimo.getValueAt(this.tableEmprestimo.getSelectedRow(), 5).toString());
            if (tableEmprestimo.getValueAt(this.tableEmprestimo.getSelectedRow(), 4) != null) {
                textDataDevolucao.setText(tableEmprestimo.getValueAt(this.tableEmprestimo.getSelectedRow(), 4).toString());
            }
        }
    }//GEN-LAST:event_tableEmprestimoMouseClicked

    private void buttonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonApagarActionPerformed
        if (evt == null) return;

        emprestimoService.deleteEmprestimoDB(Integer.parseInt(labelIid.getText()));
        labelIid.setVisible(false);
        textIdAmigo.setText("");
        textIdFerramenta.setText("");
        textDataEmprestimo.setText("");
        textDataDevolucao.setText("");
        this.CarregaListaEmprestimo();
        mostrarMensagem("Emprestimo apagado com sucesso.");
    }//GEN-LAST:event_buttonApagarActionPerformed
    public void CarregaListaEmprestimo() {
        DefaultTableModel model = (DefaultTableModel) tableEmprestimo.getModel();
        model.setRowCount(0);
        labelIid.setVisible(false);
        List<Emprestimo> listaEmprestimo = emprestimoService.listaEmprestimo();
        for (int i = 0; i < listaEmprestimo.size(); i++) {
            model.addRow(new Object[]{
                listaEmprestimo.get(i).getIDEmprestimo(),
                listaEmprestimo.get(i).getIDAmigo(),
                listaEmprestimo.get(i).getIDFerramenta(),
                listaEmprestimo.get(i).getDataEmprestimo(),
                listaEmprestimo.get(i).getDataDevolucao(),
                emprestimoService.emprestimoAtivo(listaEmprestimo.get(i).getIDEmprestimo()),
            }
            );
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmGerenciarEmprestimo().setVisible(true);
            });

    }

    protected int confirmarApagarEmprestimo() {
        return JOptionPane.showConfirmDialog(null, "Esta ação também apagará todos os empréstimos associados a este Ferramenta, deseja continuar?");
    }

    public void mostrarMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }

    protected javax.swing.JTextField getJTFIdAmigo() {
        return this.textIdAmigo;  // acesso direto porque está dentro da classe
    }

    protected javax.swing.JTextField getJTFIdFerramenta() {
        return this.textIdFerramenta;
    }

    protected javax.swing.JTextField getJTFDataEmprestimo() {
        return this.textDataEmprestimo;
    }

    protected javax.swing.JTextField getJTFDataDevolucao() {
        return this.textDataDevolucao;
    }

    protected javax.swing.JButton getJBModificar() {
        return this.buttonModificar;
    }

    protected javax.swing.JButton getJBApagar() {
        return this.buttonApagar;
    }

    protected javax.swing.JTable getJTableEmprestimo() {
        return this.tableEmprestimo;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton buttonApagar;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAtivo;
    private javax.swing.JLabel labelAtivoConstante;
    private javax.swing.JLabel labelDataDevolucao;
    private javax.swing.JLabel labelDataInicio;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelIdAmigo;
    private javax.swing.JLabel labelIdFerramenta;
    private javax.swing.JLabel labelIid;
    private javax.swing.JTable tableEmprestimo;
    private javax.swing.JTextField textDataDevolucao;
    private javax.swing.JTextField textDataEmprestimo;
    private javax.swing.JTextField textIdAmigo;
    private javax.swing.JTextField textIdFerramenta;
    // End of variables declaration//GEN-END:variables
}
