package visao;

import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Emprestimo;
import modelo.Ferramenta;
import service.EmprestimoService;
import service.FerramentaService;

public class FrmGerenciarFerramenta extends javax.swing.JFrame {

    private transient FerramentaService ferramentaService = new FerramentaService();
    private String mensagem;

    public FrmGerenciarFerramenta() {
        initComponents();
        this.carregaListaFerramenta();
    }

    public String getMensagem() {
        return mensagem;
    }

    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAmigos = new javax.swing.JTable();
        jLID = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLMarca = new javax.swing.JLabel();
        jTFMarca = new javax.swing.JTextField();
        jLCustoFerramenta = new javax.swing.JLabel();
        jTFCustoFerramenta = new javax.swing.JTextField();
        jLDisponivel = new javax.swing.JLabel();
        jBApagar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLIid = new javax.swing.JLabel();
        jLCustoTotal = new javax.swing.JLabel();
        labelDisponivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Ferramentas");

        jTableAmigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Marca", "Custo", "Disponível"
            }
        ));
        jTableAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAmigosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAmigos);

        jLID.setText("ID:");

        jLNome.setText("Nome:");

        jLMarca.setText("Marca:");

        jLCustoFerramenta.setText("Custo:");

        jLDisponivel.setText("Disponível:");

        jBApagar.setText("Apagar");
        jBApagar.addActionListener(this::jBApagarActionPerformed);
        
        jBModificar.setText("Modificar");
        jBModificar.addActionListener(this::jBModificarActionPerformed);
        
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(this::jBCancelarActionPerformed);

        jLIid.setText("0");

        jLCustoTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLCustoTotal.setText("Custo total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLIid)))
                        .addGap(156, 156, 156)
                        .addComponent(jLCustoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLCustoFerramenta)
                                            .addComponent(jLMarca))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTFMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                            .addComponent(jTFCustoFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLDisponivel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelDisponivel))
                                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(239, 239, 239))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBApagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBCancelar)
                                .addContainerGap())))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLID)
                    .addComponent(jLIid)
                    .addComponent(jLCustoTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCustoFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCustoFerramenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDisponivel)
                    .addComponent(labelDisponivel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBApagar)
                    .addComponent(jBModificar)
                    .addComponent(jBCancelar))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        //Libera todos os recurso da interface gráfica
        if (evt == null) return;

        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTableAmigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAmigosMouseClicked
        if (evt == null) return;

        if (this.jTableAmigos.getSelectedRow() != -1) {
            jLIid.setText(jTableAmigos.getValueAt(this.jTableAmigos.getSelectedRow(), 0).toString());
            jLIid.setVisible(true);
            jTFNome.setText(jTableAmigos.getValueAt(this.jTableAmigos.getSelectedRow(), 1).toString());
            jTFMarca.setText(jTableAmigos.getValueAt(this.jTableAmigos.getSelectedRow(), 2).toString());
            jTFCustoFerramenta.setText(jTableAmigos.getValueAt(this.jTableAmigos.getSelectedRow(), 3).toString());
            labelDisponivel.setText(jTableAmigos.getValueAt(this.jTableAmigos.getSelectedRow(), 4).toString());

        }
    }//GEN-LAST:event_jTableAmigosMouseClicked

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        if (evt == null) return;

        try {
            int id = Integer.parseInt(jTableAmigos.getValueAt(this.jTableAmigos.getSelectedRow(), 0).toString());
            String nome = "";
            String marca = "";
            double custo = 0;
            if (jTFNome.getText().length() < 2) {
                throw new Erro("Nome deve conter pelo menos 2 caracteres, tente novamente.");
            } else {
                nome = (jTFNome.getText());

            }
            if (jTFMarca.getText().length() < 2) {
                throw new Erro("Marca deve conter pelo menos 2 caracteres, tente novamente.");
            } else {
                marca = (jTFMarca.getText());

            }
            if (Double.parseDouble(jTFCustoFerramenta.getText()) <= 0) {
                throw new Erro("Custo deve ser maior que 0, tente novamente.");
            } else {
                custo = (Double.parseDouble(jTFCustoFerramenta.getText()));

            }
            if (ferramentaService.updateFerramentaDB(id, nome, marca, custo)) {
                mostrarMensagem("Ferramenta atualizada com sucesso.");
                jLIid.setVisible(false);
                jTFMarca.setText("");
                jTFNome.setText("");
                jTFCustoFerramenta.setText("");
                labelDisponivel.setText("");
                this.carregaListaFerramenta();
            }
        } catch (Erro erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBApagarActionPerformed
        if (evt == null) return;

        int conf = 0;
        EmprestimoService emp = new EmprestimoService();
        List<Emprestimo> listaEmprestimo = emp.listaEmprestimo();
        int idEmprestimo = 0;
        conf = confirmarApagarFerramenta();
        if (conf == 0) {

            for (int i = 0; i < listaEmprestimo.size(); i++) {
                if (listaEmprestimo.get(i).getIDFerramenta() == Integer.parseInt(jLIid.getText())) {
                    emp.deleteEmprestimoDB(listaEmprestimo.get(i).getIDEmprestimo());
                }
            }
            ferramentaService.deleteFerramentaDB(Integer.parseInt(jLIid.getText()));
            jLIid.setVisible(false);
            jTFMarca.setText("");
            jTFNome.setText("");
            jTFCustoFerramenta.setText("");
            labelDisponivel.setText("");
            this.carregaListaFerramenta();
            mostrarMensagem("Ferramenta apagada com sucesso.");
        }

    }//GEN-LAST:event_jBApagarActionPerformed
    public void carregaListaFerramenta() {
        DefaultTableModel model = (DefaultTableModel) jTableAmigos.getModel();
        jLIid.setVisible(false);
        double som = 0;
        DecimalFormat df = new DecimalFormat("0.00");
        model.setNumRows(0);
        List<Ferramenta> listaFerramenta = ferramentaService.listaFerramenta();
        for (Ferramenta objeto : listaFerramenta) {
            model.addRow(new Object[]{
                objeto.getIdFerramenta(),
                objeto.getNomeFerramenta(),
                objeto.getMarcaFerramenta(),
                objeto.getCustoFerramenta(),
                ferramentaService.getDisponivel(objeto.getIdFerramenta()),}
            );
            som += objeto.getCustoFerramenta();
        }
        jLCustoTotal.setText("Custo total: R$" + df.format(som));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciarFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGerenciarFerramenta().setVisible(true));

    }

    protected int confirmarApagarFerramenta() {
        return JOptionPane.showConfirmDialog(null, "Esta ação também apagará todos os empréstimos associados a este Ferramenta, deseja continuar?");
    }

    public void mostrarMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }

    protected javax.swing.JTextField getJTFNome() {
        return this.jTFNome;  // acesso direto porque está dentro da classe
    }

    protected javax.swing.JTextField getJTFCustoFerramenta() {
        return this.jTFCustoFerramenta;
    }

    protected javax.swing.JTextField getJTFMarca() {
        return this.jTFMarca;
    }

    protected javax.swing.JButton getJBModificar() {
        return this.jBModificar;
    }

    protected javax.swing.JButton getJBApagar() {
        return this.jBApagar;
    }

    protected javax.swing.JTable getJTableAmigos() {
        return this.jTableAmigos;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCustoFerramenta;
    private javax.swing.JLabel jLCustoTotal;
    private javax.swing.JLabel jLDisponivel;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLIid;
    private javax.swing.JLabel jLMarca;
    private javax.swing.JLabel jLNome;
    private javax.swing.JButton jBApagar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCustoFerramenta;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTable jTableAmigos;
    private javax.swing.JLabel labelDisponivel;
    // End of variables declaration//GEN-END:variables
}
