package visao;

import java.util.List;
import modelo.Amigo;
import modelo.Emprestimo;
import modelo.Ferramenta;
import java.util.logging.Level;
import java.util.logging.Logger;
import service.AmigoService;
import service.EmprestimoService;
import service.FerramentaService;

public class FrmRelatorio extends javax.swing.JFrame {

    public FrmRelatorio() {
        initComponents();
        this.criaRelatorio();
    }
    private static final Logger logger = Logger.getLogger(FrmRelatorio.class.getName());
    private transient FerramentaService ferramentaService = new FerramentaService();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        jTARelatorio = new javax.swing.JTextArea();
        javax.swing.JButton jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatório");

        jTARelatorio.setColumns(20);
        jTARelatorio.setRows(5);
        jScrollPane1.setViewportView(jTARelatorio);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (evt == null) {
            return;
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void criaRelatorio() {
        int idAmigo = 0;
        int maior = 0;
        String string = "FERRAMENTAS: \n";
        StringBuilder sb = new StringBuilder();
        double som = 0;
        AmigoService amigoService = new AmigoService();
        EmprestimoService emp = new EmprestimoService();
        List<Amigo> listaAmigo = amigoService.listaAmigo();
        List<Ferramenta> listaFerramenta = ferramentaService.listaFerramenta();
        List<Emprestimo> listaEmprestimo = emp.listaEmprestimo();

        for (Ferramenta f : listaFerramenta) {
            sb.append("\n ID da Ferramenta: ").append(f.getIdFerramenta())
                    .append("\n Nome da Ferramenta: ").append(f.getNomeFerramenta())
                    .append("\n Marca da Ferramenta: ").append(f.getMarcaFerramenta())
                    .append("\n Custo da Ferramenta: ").append(f.getCustoFerramenta())
                    .append("\n");
            som += f.getCustoFerramenta();
        }

        sb.append("\n Custo total das ferramentas: R$").append(som).append("\n\n AMIGOS: \n");

        for (Amigo a : listaAmigo) {
            int qtdEmprestimos = amigoService.quantidadeEmprestimo(a.getIdAmigo());
            boolean possuiAtivo = amigoService.possuiEmprestimoAtivo(a.getIdAmigo());

            sb.append("\n ID do Amigo: ").append(a.getIdAmigo())
                    .append("\n Nome do Amigo: ").append(a.getNomeAmigo())
                    .append("\n Telefone do Amigo: ").append(a.getTelefone())
                    .append("\n Número de Empréstimos: ").append(qtdEmprestimos)
                    .append("\n Possui empréstimo ativo: ").append(possuiAtivo)
                    .append("\n");

            if (qtdEmprestimos > maior) {
                idAmigo = a.getIdAmigo();
                maior = qtdEmprestimos;
            }
        }

        sb.append("\n Amigo com maior quantidade de empréstimos: ")
                .append(amigoService.getNomeAmigo(idAmigo))
                .append("\n Quantidade de empréstimos: ")
                .append(maior)
                .append("\n\n EMPRÉSTIMOS: \n");

        for (int i = 0; i < listaEmprestimo.size(); i++) {
            Emprestimo e = listaEmprestimo.get(i);
            logger.log(Level.INFO, "Processando empréstimo índice: {0}", i);

            sb.append("\n ID do Empréstimo: ").append(e.getIDEmprestimo())
                    .append("\n Nome do Amigo: ").append(amigoService.getNomeAmigo(e.getIDAmigo()))
                    .append("\n Nome da Ferramenta: ").append(ferramentaService.getNomeFerramenta(e.getIDFerramenta()))
                    .append("\n Data de Início: ").append(e.getDataEmprestimo())
                    .append("\n Data de Devolução: ").append(e.getDataDevolucao())
                    .append("\n");
        }
        jTARelatorio.setText(sb.toString());

    }

    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmRelatorio().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JTextArea jTARelatorio;
    // End of variables declaration//GEN-END:variables
}
